# Generated by Django 4.2.4 on 2024-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, null=True)),
                ("op1", models.CharField(max_length=200, null=True)),
                ("op2", models.CharField(max_length=200, null=True)),
                ("op3", models.CharField(max_length=200, null=True)),
                ("op4", models.CharField(max_length=200, null=True)),
                ("ans", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="questions",
            name="gfg",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.DeleteModel(
            name="Types",
        ),
    ]
